### ISSUE TITLE
Failure in go get

### ISSUE THREAD

**Issue by qabo0101** [talkkonnect/talkkonnect#10]
Having som issues:

talkkonnect@raspberrypi:~/gocode $ go get github.com/talkkonnect/talkkonnect
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

talkkonnect@raspberrypi:~/gocode/src/github.com/talkkonnect/talkkonnect $ go build -o /home/talkkonnect/bin/talkkonnect cmd/talkkonnect/main.go
../../../golang.org/x/sys/unix/affinity_linux.go:10:2: cannot find package "math/bits" in any of:
/usr/lib/go-1.7/src/math/bits (from $GOROOT)
/home/talkkonnect/gocode/src/math/bits (from $GOPATH)

Thank you / qa

**Comment by talkkonnect** [comment]
please try to use  go version go1.9 linux/arm. I recommend raspberry pi 3b+ for installations.
once built pls send some pics to add to my blog, if you have any questions dont hesitate.
