### ISSUE TITLE
how to configure talkkonnect.xml

### ISSUE THREAD

**Issue by spereg53** [talkkonnect/talkkonnect#105]
how to configure talkkonnect.xml for activate transmision mode, like android mumble clients, by audio output from two-ways radio,thanks for help

**Comment by talkkonnect** [comment]
In talkkonnect we use GPIO or httpapi or mqtt to configure transmission. there is no vox. Connect using GPIO and opto isolators is the best solution and talkkonnect was designed to support. There is no vox capabilities in talkkonnect.

**Comment by spereg53** [comment]
thanks
ING.SERGIO M.PEREZ GORDILLO
CALLE DE CHAMULA #21
COL.LA LOMITA;C.P.29060
TUXTLA GTZ.CHIAPAS,MEXICO
TEL:019612640373 y
019611214526
CELULAR:9612015537
***@***.***
***@***.***
