### ISSUE TITLE
Oled display now always updates the channel when changing channels

### ISSUE THREAD

**Issue by peterfdej** [talkkonnect/talkkonnect#107]
The Oled display  sometimes update the channel name. When you toggle (e.g. F1 next channel) the display changes when another user is using that channel and it changes when you toggle to the next channel (even when you are the only one on that channel). After that it does not change when you toggle trough empty channels, until you reach the channel where someone is using that channel.
I am using a PI3 64bits with the latest update.

**Comment by talkkonnect** [comment]
Peter,
Thanks for the detailed report, clear information and reproducible steps  that lead to the issue at hand.

From what I have understood there is 1 problem identified. The Updated Channel Name is not showing  on the OLED when channel change event happens in the case that there is only 1 participant in that channel.

I will look into this issue test it when I fix it will make the next release and then inform you and close this ticket.

**Comment by talkkonnect** [comment]
Peter,
please update to talkkonnect Version  "2.32.01" Released on "07 Nov 2023" that has fixed this issue and report back your findings so I can close this ticket.

suvir

**Comment by peterfdej** [comment]
I've updated and toggling through channels is working good. 
![IMG_20231103_121439](https://github.com/talkkonnect/talkkonnect/assets/8577555/7cc3ceed-aa2d-44d8-99bd-25ec74288af3)
My portable communication set for cameramen.
Update script is not working very well. Lost talkkonnect.xml again.

**Comment by talkkonnect** [comment]
Peter,
which update script are you using so I can fix this problem also. Please advise.

suvir

**Comment by peterfdej** [comment]
this one:
wget https://raw.githubusercontent.com/talkkonnect/talkkonnect/main/scripts/update-talkkonnect-64bit.sh

**Comment by Propeller-v8** [comment]
Survir,

culprit it is line 98 in update script, path .. "/github.old/" does not exist.

Corresponding to line 54 correction should be:
"cp /root/talkkonnect.xml  /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/talkkonnect.xml"

Greets Andre

**Comment by talkkonnect** [comment]
Ok When I get time I will fix the update scripts.

**Comment by talkkonnect** [comment]
Andre,
I have updated the update-talkkonnect-64bit.sh already to backup both the certificate and the xml config file and at the same time update to the latest version of golang. It should work properly and not cause too much headache for now.

**Comment by peterfdej** [comment]
Suvir,
Update script is working fine now for me.
However I don't think this is correct:
if [[ -f "/home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/mumble.pem" ]]
then
        echo "copying talkkonnect.xml for safe keeping to /root/"$BACKUPXML
        cp /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/talkkonnect.xml /root/$BACKUPCERT

thx.

**Comment by talkkonnect** [comment]
It is correct for those who have certificates for those who don't just
ignore the pem file

**Comment by peterfdej** [comment]
echo say: copying talkkonnect.xml instead of mumble.pem.
cp talkkonnect.xml to $BACKUPCERT

**Comment by talkkonnect** [comment]
Peter,
thanks for your feedback, I have fixed and updated the update script.
