### ISSUE TITLE
New update script - wrong cp command

### ISSUE THREAD

**Issue by Propeller-v8** [talkkonnect/talkkonnect#112]
Hi Suvir,

there is a wrong cp argument in the new update script:

line 56 + 57 should be:
echo "copying mumble.pem for safe keeping to /root/"$BACKUPCERT
cp /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/mumble.pem /root/$BACKUPCERT

line 109 should be:
cp /root/$BACKUPCERT /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/mumble.pem

greets Andre

**Comment by talkkonnect** [comment]
Hi Andre,

Thank you for your observation and feedback, I have fixed the update script as requested.

Best Regards,

Suvir Kumar
