### ISSUE TITLE
Combine "comitup" into your images

### ISSUE THREAD

**Issue by Alaric84** [talkkonnect/talkkonnect#127]
do you know the comitup project:

https://github.com/davesteele/comitup/wiki/Installing-Comitup

This would make your images much more flexible and portable.

**Comment by talkkonnect** [comment]
Alaric,
ok thanks for the suggestion in the next iteration of the image release, which i do about every 6 momths I will include this wifi configuration tool to make it easier for users to get started on a wifi connection.

thank you
suvir
