### ISSUE TITLE
ledstrip documentation formatting

### ISSUE THREAD

**Issue by Alaric84** [talkkonnect/talkkonnect#128]
I'm wondering about this documentation lines

https://github.com/talkkonnect/talkkonnect/blob/32f72b81504ce0f2a44532c94b988b6cac82e9b9/README.md?plain=1#L703C1-L704C60

the markdown rendering and maybe the content too looks suspicious.

With the led strip this should be enabled true?
The two lines should be marked in a code section.

Thanks for the great repo!

**Comment by talkkonnect** [comment]
Akaric84
fixed the error in documentation and marked in code section as suggested.

suvir
