### ISSUE TITLE
Multiple LCD/OLED

### ISSUE THREAD

**Issue by gilliangoud** [talkkonnect/talkkonnect#136]
Hi!

I've searched through the configs, code and issues and wanted to verify that at this moment in time 
only 1 display is supported, right?

I was thinking of making something like this:
![image](https://github.com/user-attachments/assets/682eaed5-d8f4-40e5-afb8-81487475a8f8)

**Comment by talkkonnect** [comment]
The current use case as a desktop transceiver/intercom one display is sufficient. Yes currently only one display is supported.

**Comment by talkkonnect** [comment]
If the messages you want to display are simple for example offline/online or speaking etc etc you can use LEDs to do that with a little modification of the code since talkkonnect supports the mcp23017 there are 100s of outputs available.
