### ISSUE TITLE
On-by-default PTT

### ISSUE THREAD

**Issue by SecareLupus** [talkkonnect/talkkonnect#137]
Hello, I'm working on an embedded project without buttons for PTT, but with headphones with built-in mute switches. Is there an easy way to set PTT default to on?

My current process involves sending an HTTP request to `?command=startTransmitting` after connection is established, but this solution seems brittle in the event of loss of connections, and I don't know the best way to ensure the command is timed for _after_ the talkkonnect client has established connection and started its HTTP server. For now, I've been putting it on a standardized delay that _should_ be long enough, but I'm not sure if that's reliable.

**Comment by talkkonnect** [comment]
There is a tag txonstart change that from false to true and talkkonnect will be transmitting since connecting to server.
Then there is another tag txafterstart to set the amount of seconds delay to wait before starting to transmit upon connect.

**Comment by SecareLupus** [comment]
This worked great! Thank you!
