### ISSUE TITLE
systemd service solution

### ISSUE THREAD

**Issue by umekzg** [talkkonnect/talkkonnect#15]
This works for me...

[Unit]
Description = talKKonnect
After = multi-user.target

[Service]
User = pi
StandardInput=tty-force
ExecStart = /usr/bin/sudo /home/talkkonnect/bin/talkkonnect
Restart = always
RestartSec = 2

[Install]
WantedBy = multi-user.target

**Comment by talkkonnect** [comment]
For me I prefer to run talkkonnect in a screen so I use the below script. Anyway appreciate your feedback it will be valuable to many others.

[Unit]
Description=TalKKonnect Radio Screen
Requires=systemd-user-sessions.service network.target sound.target dbus.socket
After=multi-user.target
AllowIsolate=true

[Service]
RemainAfterExit=no
User=
Group=
Type=forking
WorkingDirectory=
ExecStartPre=
ExecStart=/usr/bin/screen -dmS tk /home/talkkonnect/bin/talkkonnect
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s SIGTERM $MAINPID
PrivateTmp=true

Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
Alias=talkkonnect.target
