### ISSUE TITLE
feature request: remote control icom ic-7100 

### ISSUE THREAD

**Issue by iw0red** [talkkonnect/talkkonnect#17]
Hi, is it possible to realize a remote control for icom ic-7100 or something like that adding  some other software?
73 Marco IW0RED.

**Comment by talkkonnect** [comment]
Technically it should be possible to use the RC-28 to control the icom. However as icom says in their website "The RC-28 is not a standalone control for Icom radios and may only be used with the RS-BA1 software". I guess the only way would be to reverse engineer their USB protocol. You would have to use a tool such as Openrazer to capture the PCAP and see what the how the official program communicates with the icom ic-7000 radio. You could then implement an additional module in go for talkkonnect which could be controlled by http api. I don't know the legalities of such a endeavor, however it should be technically possible.
73 Suvir
