### ISSUE TITLE
Error build  by talkkonnect

### ISSUE THREAD

**Issue by fft01** [talkkonnect/talkkonnect#24]
Hello,

when i build the talkkonnect program i get the following error:

BackLightTime.Reset undefined (type * time.Ticker has no field or method Reset)

What am I doing wrong?

Kind regards
Dirk

**Comment by zrdimetc** [comment]
Hi Dirk. You are correct. We have seen this problem before in the talkkonnect community. Kindly please refer to an excellent [README](https://github.com/talkkonnect/talkkonnect/blob/master/README.md) document from Suvir. He put a lot of effort into documenting [talkkonnect](https://talkkonnect.com/). Solution to the problem you are reporting is ...You need to update your [go version](https://golang.org/dl/) to at least v1.15. Currently [v1.15.3](https://golang.org/dl/). Regards.

**Comment by talkkonnect** [comment]
Yes please follow the instructions in the blog do not use apt-get to install golang.
