### ISSUE TITLE
Have Channel up key loop to beginning again if end of list is reached

### ISSUE THREAD

**Issue by andrewhearn** [talkkonnect/talkkonnect#26]
A small suggestion...

It may be useful to some people for the Channel Up key (F1) and it's corresponding GPIO button to loop through the channels rather than to get to the end of the channel list and say 'Can't Increment Channel Maximum Channel Reached'.

This would mean you can have a single button to cycle through the channels rather then needing to have 2 buttons.

eg, if I only have 2 channels, I can keep pressing F1 (or the GPIO button) to go between them - and if there are 3 or more channels, then it would just carry on looping through all of them.

**Comment by talkkonnect** [comment]
Suggestion Accepted. Thank you for your feedback.

Suvir
