### ISSUE TITLE
How to automatically start transmitting ?

### ISSUE THREAD

**Issue by kovalroma** [talkkonnect/talkkonnect#29]
Hello,
How to automatically start transmitting on program boot?
Is it possible to add some parameters to **talkkonnect-run** ?

**Comment by zrdimetc** [comment]
@kovalroma. Do you want to use a microphone to go on a transmission 
or stream an audio source or file with gumble ffmpeg? 

Please check your `client.go` file and look for talkkonnect init function, 
`func (b *Talkkonnect) Init() {`
...
then find line,
`b.Connect()`
...
you can allow for a short delay after connecting,
`time.Sleep(200 * time.Millisecond)`
and then call the transmitting function F11 to stream audio 
or F8 for a microphone,
`b.commandKeyF11()`
or
`b.commandKeyF8()`

talKKonnect is a highly versatile framework that gives you a freedom to implement almost any 
communication logic when working with Mumble and PTT. 

Regards, Zoran

**Comment by zrdimetc** [comment]
@kovalroma. If you want to command your talKKonnect to start transmitting directly from a bash script you can also use http API functions Suvir had created. For instance, `curl http://talkkonnect_ip_address:8080/?command=F8` will make talKKonnect transmit. You could also add http API command to a service file used to start talKKonnect. Other talKKonnect http API commands are:

Channel Up
`http://talkkonnect_ip_address:8080/?command=F1`

Channel Down
`http://talkkonnect_ip_address:8080/?command=F2`

Mute/UnMute Speaker
`http://talkkonnect_ip_address:8080/?command=F3`

Current Volume Level
`http://talkkonnect_ip_address:8080/?command=F4`

Volume Up
`http://talkkonnect_ip_address:8080/?command=F5`

Volume Down
`http://talkkonnect_ip_address:8080/?command=F6`

API List Server Channels
`http://talkkonnect_ip_address:8080/?command=F7`

Start Transmitting
`http://talkkonnect_ip_address:8080/?command=F8`

Stop Transmitting
`http://talkkonnect_ip_address:8080/?command=F9`

List Online Users
`http://talkkonnect_ip_address:8080/?command=F10`

Play/Stop Chimes
`http://talkkonnect_ip_address:8080/?command=F11`

Request GPS Position
`http://talkkonnect_ip_address:8080/?command=F12`

Send Email
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlE`

Previous Server
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlF`

Next Server
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlN
`
Clear Screen
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlL`

Ping Servers
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlO`

Panic Simulation
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlP`

Repeat Tx Loop Test
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlR`

Scan
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlS`

Show Acknowledgements
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlT`

Current Version
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlV`

Print XML Config
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlX`

Traffic Recording
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlI`

Ambient (Mic) Recording
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlJ`

Combo (Traffic and Mic) Recording
`http://talkkonnect_ip_address:8080/?command=commandKeyCtrlK`

**Comment by kovalroma** [comment]
Thank you for such detail answer.
