### ISSUE TITLE
Joining passcoded channel/sub channel from startup

### ISSUE THREAD

**Issue by balkan16** [talkkonnect/talkkonnect#31]
Hi!! Thanks for the project, have been looking for this exact project for the past 2 months. It really helped me a lot. I've been wondering could the **raspi(talkkonnect)** join a **specific passcoded channel/sub-channel from the startup**? I've been looking through the XML code and the tutorial. Seems there's **no specific place to tell the password of the channel**.

**Comment by talkkonnect** [comment]
In the account tag there is an xml element called channel

**Comment by balkan16** [comment]
I've already done that, the problem is when the channel/sub-channel has a password on it. How do i insert the password  so i could automatically join that "secured channel"?

**Comment by talkkonnect** [comment]
Have never tested with a secure subchannel before. Question does this work if you connect to the root channel first then change channel? Or does it also not work that way? Just want to know cause never tested to connect to a secure channel. Will have to look at humble library documentation.

**Comment by balkan16** [comment]
From root, then move to another channel(without password) works perfectly. But if there's a password, the only choice i have is to move talkkonnect to that particular channel as an admin. 
There's also a problem which **admin couldn't register talkkonnect**, if the admin could register talkkonnect, it wouldn't have to go back to Root again after every startup.

**Comment by talkkonnect** [comment]
According to the docs I have read and remember, this may be inaccurate, but it seems all client "Have to" connect to the root channel first, they they are moved after connection. This is what happens in the gumble library. That is why I think when you connect to a server with normal password and move to a normal channel that has no special password for that channel it works. What I am thinking is that maybe something is broken with the password authentication on talkkonnect or maybe we are not following the mumble protocol rules for password protected channels. At this point I really don't know the cause but if you can figure it out do let me know. When I have time later I will look into this issue, as i have never tried this use-case before. Maybe reading the mumble protocol documentation will give some idea how to solve this problem and how authentication for individual channels works in mumble.

**Comment by balkan16** [comment]
Sure, I appreciate your effort! Thanks for the response.

**Comment by talkkonnect** [comment]
I think you may have to use a certificate for that. Can you try to use a certificate and let me know if it works for our use case? Without the certificate I don't think you can register a user on a channel. So its something to do with requiring a certificate. Let me know how you get a log. As for how to generate a certificate there are some instructions in the talkiepi page.

**Comment by balkan16** [comment]
Yes, the certificate works perfect, now I could register talkkonnect and automatically assign it to a specific secured channel after every startup! Thanks for the solution.
