### ISSUE TITLE
When testing first launch, terminal echo is turned off if an error occurs during startup

### ISSUE THREAD

**Issue by iammeat** [talkkonnect/talkkonnect#33]
I am using the latest OS for the Raspberry Pi 4, and I installed a fresh copy of talkkonnect.  When I run it the first time, I got an error that /var/log/talkkonnect.log couldn't be accessed.  Not a problem, as I prefer to put the logs in the home folder of the software.  

I then tried to edit the config to put this new path in, but when I got the error message my terminal no longer showed characters as I typed them.  I re-enabled echo using ```stty echo``` and this fixed the problem (though my cursor was still invisible), but you might want to check you're turning echo back on again on error exit.

**Comment by talkkonnect** [comment]
As a work around you can type reset to reset the terminal. It is a known problem from the library used termboxgo
Thank you for your feedback.

suvir
