### ISSUE TITLE
Suggestion: Add AttentionLED pulse command

### ISSUE THREAD

**Issue by cschriel** [talkkonnect/talkkonnect#37]
Instead of only turning the attentionled on or off, i would like to have it flash for a defined period of time. 

Usecase: Press a "call" or "attention" button on a client that sends an mqtt topic attentionled:flash (just like relay1:pulse), which in result will let the led flash 20 times on other clients.

Also mentioned by @andrewhearn in issue #27

**Comment by talkkonnect** [comment]
As a quick fix to implement what you want 

there is a source code  file /home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/mqtt.go in talkkonnect directory specifically the line 284 with the code

       case "attentionled:on":
                log.Println("info: MQTT Turn On Attention LED Successfully\n")
                b.LEDOn(b.AttentionLED)
 
with the minimal modification you can change it to

      case "attentionled:on":
                log.Println("info: MQTT Blink Attention LED 20 times Successfully\n")
                for i := 0; i < 20; i++ {
                        b.LEDOn(b.AttentionLED)
                        time.Sleep(300 * time.Millisecond)
                        b.LEDOff(b.AttentionLED)
                        time.Sleep(300 * time.Millisecond)
                }

change the times from 20 to whatever you want and adjust the time delay from 300 to whatever you feel is good for your use case.

then recompile if you are using the image you can do /root/compile to recompile it.

Hope this will get you what you want quickly.

Suvir
