### ISSUE TITLE
Image Zip Won't Extract

### ISSUE THREAD

**Issue by retrospectsecurity** [talkkonnect/talkkonnect#38]
Hi I downloaded the usb sound card image and extracting the size goes to over 9gb then fails. what size is the image? thanks.

**Comment by talkkonnect** [comment]
You will need a 16GB SD card for this image. That's the smallest currently available size in my area so I had to use it. Let me know how you get along with a SD card that has a capacity of 16GB or greater.

**Comment by zrdimetc** [comment]
If your downloaded file is corrupted, try to clear internet browser cache, or use another browser. Try different internet connection.

**Comment by talkkonnect** [comment]
Allow me to close this ticket as we cannot reproduce this here.
