### ISSUE TITLE
can not communicate with wpa_supplicant

### ISSUE THREAD

**Issue by spereg53** [talkkonnect/talkkonnect#39]
i downloaded mems microphone image for raspberry  and can not connect to wifi,after sudo raspi-config ,wireless lan and give the message that can no comunicate with wpa_supplicant,wha can i do???

**Comment by spereg53** [comment]
![IMG_20210716_191345258](https://user-images.githubusercontent.com/5591045/126020024-d09b5bcc-7a11-423a-89e1-c2ac6f1c942b.jpg)
![IMG_20210716_191357000](https://user-images.githubusercontent.com/5591045/126020030-247032ac-966a-4d49-bf04-a4c5030797cd.jpg)

**Comment by talkkonnect** [comment]
Are you running as root you should be running as root

**Comment by talkkonnect** [comment]
also with googlefu other users using raspberry pi solved the same problem by using the following command to debug

sudo wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0 -d

**Comment by zrdimetc** [comment]
Edit your `wpa_supplicant.conf` file

`nano /etc/wpa_supplicant/wpa_supplicant.conf`

Add your own wireless network information

```
network={
ssid="your_ssid_name"
psk="your_wifi_password"
}
```

Restart wpa_supplicant service

`service wpa_supplicant restart`

**Comment by spereg53** [comment]
thanks ,i did modify wpa_supplicant manual mode
ING.SERGIO M.PEREZ GORDILLO
CALLE DE CHAMULA #21
COL.LA LOMITA;C.P.29060
TUXTLA GTZ.CHIAPAS,MEXICO
TEL:019612640373 y
019611214526
CELULAR:9612015537
***@***.***
***@***.***
