### ISSUE TITLE
Small typo in line 216.

### ISSUE THREAD

**Issue by McPeebs** [talkkonnect/talkkonnect#5]
https://github.com/talkkonnect/talkkonnect/blob/45c8c399432c1870bc1559368ff3935211095903/talkkonnect.xml#L216

Instructions for target board says to put "pc" for both rpi and pc configs.

**Comment by talkkonnect** [comment]
McPeebs,
thank you for for your feedback typos fixed also created additional directory called sample-configs for many different scenarios of hardware.
