### ISSUE TITLE
talkkonnect.xml hearbeat configuration

### ISSUE THREAD

**Issue by pe-jot** [talkkonnect/talkkonnect#53]
I had difficulties getting the heartbeat timing configuration working, especially because I misunderstood the meaning of "ledonmsecs" and "ledoffmsecs". They work like an absolute value measured from the beginning of the cycle, and not as I understood, as relative values.

In addition to this, the sample has only 10 msecs "on" time (from 1000 to 1010 msecs) so I initially thought it was not working at all because I didn't recognize a pin change.

Thus, I request to either extend the documentation or e.g. change ledoffmsecs to 2000 in the example configuration, please.

Thanks!

**Comment by talkkonnect** [comment]
Thanks for your work it looks very cool, and it is the kind of project that builds on talkkonnect which makes my mission to create talkkonnect successful. I want to work on web config for talkkonnect with maybe SQLite as backend. But unfortunately I don’t yet know web programming and have a lot to learn. If possible if you can send photos of your build working with icon transceiver so I can post on my blog to inspire others to create their own projects.

You can go ahead and close this issue.
