### ISSUE TITLE
Autoprovision.go Bug

### ISSUE THREAD

**Issue by ChZeman** [talkkonnect/talkkonnect#55]
There is a problem in line 76 of autoprovision.go.

`err := downloadFile(Config.Global.Software.AutoProvisioning.SaveFilePath, Config.Global.Software.AutoProvisioning.SaveFilePath, fileURL)`

Config.Global.Software.AutoProvisioning.SaveFilePath is passed twice. Config.Global.Software.AutoProvisioning.SaveFilSaveFileName should be the second item, but it's not defined.

`./autoprovision.go:76:115: Config.Global.Software.AutoProvisioning.SaveFileName undefined (type struct { Enabled bool "xml:\"enabled,attr\""; TkID string "xml:\"tkid\""; URL string "xml:\"url\""; SaveFilePath string "xml:\"savefilepath\""; SaveFilename string "xml:\"savefilename\"" } has no field or method SaveFileName, but does have SaveFilename)`

I got around this by changing the second "Config.Global.Software.AutoProvisioning.SaveFilePath" to "talkkonnect.xml."

Thank you,
Chris

**Comment by talkkonnect** [comment]
Bug Fixed thank you for the testing and bug report Chris.

**Comment by ChZeman** [comment]
Thank you, Suvir! I'd like to add that my fix renders the <savefilename> directive in talkkonnect.xml useless, but that probably doesn't matter unless someone wants to save it as a different filename for some reason.
