### ISSUE TITLE
How to transmit "aplay Systemsound"  as default input source

### ISSUE THREAD

**Issue by p1337** [talkkonnect/talkkonnect#57]
Hallo there, 

I am running a raspi 4 with a mumble server and a talkkonnect client.
Talkkonnect is starting at startup and connecting after 30 seconds to the localhost mumble server.
I have edited the client.go -> so that the client ist transmitting after connecting to the server.

What I want to do: is stream an "APLAY Systemsound Stream" to the Mumble Server, because I am running a rtl_sdr (software defined radio) that plays directly to aplay) 

`rtl_fm -f 87175000 -s 44100 -g 9 -l 0 - | aplay -t raw -r 44100 -c 2 -f S16_LE`

here comes the part, where I am not shure, if I had done it right.

I have activated the alsa loopback modules
I have uninstalled pulse audio, so the loopback is the default audio source ( I think, so )

No sound is arriving at the Mumble Server.

When I am using the card 1 (then my headphones are getting the right output)

`rtl_fm -f 87175000 -s 44100 -g 9 -l 0 - | aplay -D hw:1,0,0 -t raw -r 44100 -c 2 -f S16_LE`

aplay -l output:
```

pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 7/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 2: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

arecord -l output:

```
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 7/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
```

Is there a best practice solution?
How could I troubleshoot and test if the loopback is getting the right sound?

oh - and the F11 ( internet-radio stream ) is transmitted without any problems...

- maybe the loopback is empty 
- or talkkonnect is not listening to the default device.... 

Greetings from Stuttgart / germany
Robert

**Comment by talkkonnect** [comment]
Never done this but have a look here
https://stackoverflow.com/questions/43480867/linux-pipe-audio-file-to-microphone-input

**Comment by p1337** [comment]
Okay, time to fiddle it out - was to long. 
I took an USB-Soundcard - as "line-in" - and the soundoutput form the raspi built-in jack  and bridged them with an audio cable. 
Not the best way to solve this problem, I guess, but it worked within 2 minutes after a little bit of tweaking the settings.

**Comment by talkkonnect** [comment]
Ok this use case was not ever imagined but do let us know if you find a clever hack using purely software. Since we are using pure alsa and not pulse audio I don’t know if a program like jack would work or not.

**Comment by zrdimetc** [comment]
You had a good approach to use `snd_aloop` Alsa loopback module, but custom ALSA config is not something
you can spin up in a minute. For your case, you need to design `.asoundrc` and use ALSA plugs, 
like `dmix `and `dsnoop`. You are looking at some ALSA reading, making notes and experimenting.

Unofficial ALSA Wiki is here: [https://alsa.opensrc.org](https://alsa.opensrc.org)
ALSA forums are better place to ask ALSA config questions, provided you have gone through 
a lot of reading about ALSA and its traps: [https://github.com/opensrc/alsa/issues](https://github.com/opensrc/alsa/issues)
ALSA wiki info about .asoundrc is here: [https://www.alsa-project.org/main/index.php/Asoundrc](https://www.alsa-project.org/main/index.php/Asoundrc)
Another good ALSA source: [https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture](https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture)

[Pulseaudio](https://www.freedesktop.org/wiki/Software/PulseAudio) was created to simplify Linux sound management, but Pulseaudio has its many traps too.
Most tools for managing pulseaudio and [jackd](https://jackaudio.org) are desktop apps.

1. You can use [pavucontrol](https://freedesktop.org/software/pulseaudio/pavucontrol) "monitor" option to send output to input.
2. You can use tools like [QjackCtl](https://qjackctl.sourceforge.io) and [Patchage](https://drobilla.net/software/patchage.html) with jackd and pulseaudio / pulseaudio module jack to manage pulseaudio "sinks" and "sources" and "patch" 
them together.
3. To route rtl sdr audio to Mumble channel you could have used an official Muble client with "continuous" TX mode and one of the above methods involving pulseaudio, jackd and QjackCtl.

**Comment by zrdimetc** [comment]
@p1337. Robert, here is a workaround for you for streaming rtl sdr source over talKKonnect to Mumble network... 
Install `vlc` and `sox` packages on your Pi.
Run: `rtl_fm -g50 -f 96.9M -M wfm -s 180k -E deemp | sox -traw -r180k -es -b16 -c1 -V1 - -t flac - | cvlc - --sout '#standard{access=http,mux=ogg,dst=:8888/audio.ogg}'`
In `talkkonnect,xml` set your http stream source: `<sound event="stream" file="http://your_ip_address:8888" volume="50" blocking="true" enabled="true"/>`
Get more vlc information here: `https://wiki.videolan.org/Documentation:Documentation` 
and here: `https://docs.videolan.me/vlc-user/3.0/en/advanced/index.html`
If you run as pi user, vlc will run fine. If running as root you have to tune privileges or just edit vlc binary:
```
root@tk-demo-04:~ # cvlc
VLC is not supposed to be run as root. Sorry.
If you need to use real-time priorities and/or privileged TCP ports
you can use /usr/bin/vlc-wrapper (make sure it is Set-UID root and
cannot be run by non-trusted users first).
root@tk-demo-04:~ # sed -i 's/geteuid/getppid/' /usr/bin/vlc
root@tk-demo-04:~ # cvlc
VLC media player 3.0.12 Vetinari (revision 3.0.12-1-0-gd147bb5e7e)
```
This is vlc playing piped audio from rtl_fm and sox player
```
root@tk-demo-04:~ # ./rtlsdr.sh
rtl_fm: no process found
play: no process found
aplay: no process found
/root/rtlsdr.sh: no process found
VLC media player 3.0.12 Vetinari (revision 3.0.12-1-0-gd147bb5e7e)
Found 1 device(s):
  0:  Realtek, RTL2832UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
[0014e4f8] main interface error: no suitable interface module
[000c7258] main libvlc error: interface "globalhotkeys,none" initialization failed
[0014e4f8] dummy interface: using the dummy interface module...
[6eb03030] mux_ogg mux: Open
Detached kernel driver
Found Rafael Micro R820T tuner
Tuner gain set to 49.60 dB.
Tuned to 97170000 Hz.
Oversampling input by: 6x.
Oversampling output by: 1x.
Buffer size: 7.59ms
Exact sample rate is: 1080000.025749 Hz
Allocating 15 zero-copy buffers
Sampling at 1080000 S/s.
Output at 180000 Hz.
```

Slight disadvantage of this approach is that you wont be able to use the same Pi for sending stream and receiving stream! One Pi will pipe `rtl_fm->sox->vlc`  and some other talKKonnect client needs to start F11 or http api for source streaming
