### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by KB6mcc** [talkkonnect/talkkonnect#60]
Need help on default sound volume level setting.. Looks around within the talkkonnect.xml but not sure which section is for the 
default volume setting..  Help is appreciated

**Comment by talkkonnect** [comment]
The default volume is set in alsa and stored with "alsactl store" onto hard disk. During the usage session you can use talkkonnect to change the volume. After reboot the volume level goes back to what is set in alsamixer and saved with "alsactl store".

**Comment by KB6mcc** [comment]
Appreciated!!b It works.👍👍
