### ISSUE TITLE
Question: Mqtt tts message

### ISSUE THREAD

**Issue by off112a** [talkkonnect/talkkonnect#64]
Hi, 

Love your talkkonnect.

I wonder if it would be possible to make a mqtt command to send a tts message? For example a message that says that dinner is ready.

**Comment by talkkonnect** [comment]
As of current version tts is supported by httpapi only. I have not yet made mqtt support text to speech. Should. Not be too difficult to do it. You can copy the concept from httpapi.go to mqtt.go if you can program in golang.

**Comment by off112a** [comment]
Ok, thank you for your answer. Unfortunately, I have no experience in golang.

**Comment by talkkonnect** [comment]
Will using httpapi solve your problem?

**Comment by off112a** [comment]
I'm using Home Assistant with mqtt so I haven't tried httpapi. But I think it can be done if I have the right command for tts.

**Comment by talkkonnect** [comment]
http://192.168.10.3:8080/?command=ttsannouncement&ttsmessage=%22dinner%20is%20ready%22&ttslocalplay=true&ttsplayintostream=false&gpioenabled=false&gpioname=relay0&language=en

change the 192.168.1.3 to your talkkonnect local ip ths command will announce dinner is ready over the speaker
alternatively you can test from your browser first

hope this solution works for you

**Comment by off112a** [comment]
Thank you. It works perfect. 🙂

Do you think you will implement this for mqtt in the future?

**Comment by talkkonnect** [comment]
That was the original plan to make announcements and tts work with mqtt. However these days very busy with work so less time to develop talkkonnect. Maybe in the future let’s see.
