### ISSUE TITLE
Serial tunnel request

### ISSUE THREAD

**Issue by ON4BCB** [talkkonnect/talkkonnect#80]
Would it be possible to forsee the possibility to add a "serial bridge" between a talkkonnect client and server

in order to remote control a frontpanel ?

**Comment by talkkonnect** [comment]
Can you elaborate your use case please? What I understand is you want talkkonnect to accept commands over serial port. This serial port will be connected to what exactly? A Linux System? Or Embedded System? I need to understand what you are trying to do. Currently talkkonnect supports http api calls and also mqtt. If it is a pc or embedded system controlling talkkonnect you should be able to control it via those 2 provided protocols. So I need to understand more. Thanks.

**Comment by ON4BCB** [comment]
Hi Suvir

I use talkkonnect client and server on a raspberry pi (any PI3/4 or zero)
to transport audio in both directions  + PTT by GPIO

I have a radio where i can remove the frontpanel, (ex kenwood TS480,
elecraft K3/K3zero) which has a serial connection

I want to connect the frontpanel to the talkkonnect client, the radio to
the server

In stead of using a separate "socat/ser2net" connection it would be nice to
have this integrated in talkkonnect (sort of serial bridge)

It also can be used to remotly control a serial antenna controller or SSPA
or even any radio with a serial CAT connection

I hope my answer is clear enough

Many thanks for getting back and the very nice talkkonnect project

73

Walter ON4BCB

Op zo 19 mrt 2023 om 03:16 schreef Suvir Kumar ***@***.***>:

**Comment by talkkonnect** [comment]
Hi Walter,
thank you for your feedback and feature request, as of now I do not see integrating serial into talkkonnect as we are already using serial for gps. However if you use ser2net and start it in systemd at the same time as talkkonnect and kill it at the same time, I would think that it is a good work around that will be seamless with talkkonnect. I am trying to keep talkkonnect as light as possible. So i try to stick to core functionality only. The problem with golang is it is not like the "c" language where you can write functionality as loadable plugins. In golang everything is a single program and this carries extra weight for all modules so I have to be very selective of what is added to talkkonnect. Hope you understand the situation.

73

suvir kumar
