### ISSUE TITLE
Rotary Encoder With Button GPIO Error

### ISSUE THREAD

**Issue by mudislandkid** [talkkonnect/talkkonnect#84]
I've just managed to get hold of a rotary encoder and tried setting it up for the first time. I'm trying to make use of the new functionality that would allow me to adjust both volume and mumble channel. However whenever I set the button GPIO to true, no matter what GPIO I set it to I get an error saying: -

`Config Error [Section GPIO] Enabled GPIO Name button Pin Number 22 Invalid Name`

At the moment I have Rotary A set to GPIO 17, Rotary B set to GPIO 18 and I have to change Button to something else as by default it is also 18, so have set it to 22. 

I'm using the sample config for USB and GPIO. Raspberry Pi3B, No GPIO expander.

Am I doing something wrong?

Many Thanks.

**Comment by talkkonnect** [comment]
change the name button to rotarybutton in the xml and try again
