### ISSUE TITLE
multiple server

### ISSUE THREAD

**Issue by f59465-Clem** [talkkonnect/talkkonnect#94]
Hi to all,

How to add a second server?
Can you do audio detection from one server to another?

Thank
Clem

**Comment by talkkonnect** [comment]
Just add another XML block for the server and there are next server and previous server commands where you can change server.

**Comment by talkkonnect** [comment]
This is an example of 3 servers

![servers-sample](https://github.com/talkkonnect/talkkonnect/assets/42717241/ec71fc10-fbde-4046-afdb-3471ba6e4e2f)

**Comment by f59465-Clem** [comment]
Ok Suvir, 
I did like this before seeing the message, I have the CTRL+N "Next Server" command which does not work...

<accounts>
    <account name="community" default="true">
      <serverandport>server.com:10210</serverandport>
      <username>Relais_446</username>
      <password>****</password>
      <insecure>true</insecure>
      <register>false</register>
      <certificate></certificate>
      <channel>HAM-CB</channel>
      <ident>Name Surname</ident>
          <listentochannels>
                <channel>talKKonnect</channel>
          </listentochannels>
      <tokens enabled="true">
        <token>111111</token>
        <token>222222</token>
      </tokens>
      <voicetargets>
        <id value="0">
            <user>suvir-demo</user>
        </id>
        <id value="1">
          <users>
            <user>suvir-ubunbtu</user>
          </users>
        </id>
        <id value="2">
          <users>
            <user>suvir-demo</user>
          </users>
        </id>
        <id value="3">
          <channels>
            <channel>
              <name>TEST1</name>
              <recursive>true</recursive>
              <links>true</links>
              <group>"all"</group>
            </channel>
          </channels>
        </id>
      </voicetargets>
    </account>
	<account name="Server2" default="true">
      <serverandport>server_perso.net:64993</serverandport>
      <username>Relais_Perso_Test</username>
      <password>****</password>
      <insecure>true</insecure>
      <register>false</register>
      <certificate></certificate>
      <channel>HAM-CB</channel>
      <ident>Name Surname</ident>
          <listentochannels>
                <channel>talKKonnect</channel>
          </listentochannels>
      <tokens enabled="true">
        <token>111111</token>
        <token>222222</token>
      </tokens>
      <voicetargets>
        <id value="0">
            <user>suvir-demo</user>
        </id>
        <id value="1">
          <users>
            <user>suvir-ubunbtu</user>
          </users>
        </id>
        <id value="2">
          <users>
            <user>suvir-demo</user>
          </users>
        </id>
        <id value="3">
          <channels>
            <channel>
              <name>TEST1</name>
              <recursive>true</recursive>
              <links>true</links>
              <group>"all"</group>
            </channel>
          </channels>
        </id>
      </voicetargets>
    </account>
  </accounts>

**Comment by talkkonnect** [comment]
Clem,
I have found issue with next server and have fixed it now it is mapped to key ctrl-Q for next server make sure you have the tag nextserver index in your talkkonnect.xml file.

updated version fixed bug and released in version  2.31.01 Rel 27 Aug  2023

thanks for your bug report,
suvir kumar

**Comment by talkkonnect** [comment]
![image](https://github.com/talkkonnect/talkkonnect/assets/42717241/5cf4f054-5afe-48cd-beb9-376e41174359)

**Comment by f59465-Clem** [comment]
Reopening.
