### ISSUE TITLE
Error in install script tkbuild-32bit.sh

### ISSUE THREAD

**Issue by ahk97** [talkkonnect/talkkonnect#97]
Script ./tkbuild-32bit.sh seems to run fine. However, it throws one error:

```
mv: cannot move '/home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect' to a subdirectory of itself, '/home/talkkonnect/gocode/src/github.com/talkkonnect/talkkonnect/talkkonnect'
=> Finished building TalKKonnect

```

**Comment by talkkonnect** [comment]
Please use raspi-talkkonnect to build instead it is in the scripts directory. The build32 and build64 are depreciated. However the error you show above should not affect the building process. Can you try with rasp-talkkonnect and see its a menu driven build which is much simpler to use. Do let me know your results.

**Comment by talkkonnect** [comment]
Thank you for the report I have fixed the tkbuild-32bit.sh and also the tkbuild-64bit.sh scripts based on your feedback.

**Comment by ahk97** [comment]
Thank you!
I will also test the raspi-talkconnect later today

**Comment by talkkonnect** [comment]
If the symbolic links exist then it just means that this script has been
run before or that golang is already installed. There should be no errors
on a fresh os install when running this step item menu 3.

**Comment by ahk97** [comment]
OK. Thanks.
I used the updated tkbuild-32bit.sh script and it was working fine.
